import img from './img/img.jpeg'
import imgTwo from './img/imgTwo.png'

export const Realtor = [
    {
        id: 1,
        img: [img, imgTwo],
        title: "Casa San Diego",
        desc: "Descripcion corta",
        price: 2000,
        metrosUno: 100,
        metrosDos: 100,
        habitaciones: 4,
        banos: 2,
        estac: 2,
        ubicacion: "San Diego",
        tipo: "Casa",
        ubi: 'Ubicacion escrita',
        caracteristicas: ["134 Mts2", "Para 3 personas", "4 Habitaciones", "2 baños", "Cómodo", "Pozo de agua"]
    },
    {
        id: 2,
        img: [img, imgTwo],
        title: "Apartamento Valencia",
        desc: "Descripcion corta",
        price: 6000,
        metrosUno: 100,
        metrosDos: 100,
        habitaciones: 2,
        banos: 2,
        estac: 2,
        ubicacion: "Valencia",
        tipo: "Apartamento",
        ubi: 'Ubicacion escrita',
        caracteristicas: ["134 Mts2", "Para 3 personas", "4 Habitaciones", "2 baños", "Cómodo", "Pozo de agua"],
    },
    {
        id: 3,
        img: [img, imgTwo],
        title: "Casa Guacara",
        desc: "Descripcion corta",
        price: 10000,
        metrosUno: 100,
        metrosDos: 100,
        habitaciones: 3,
        banos: 2,
        estac: 2,
        ubicacion: "Guacara",
        tipo: "Casa",
        ubi: 'Ubicacion escrita',
        caracteristicas: ["134 Mts2", "Para 3 personas", "4 Habitaciones", "2 baños", "Cómodo", "Pozo de agua"]
    },
    {
        id: 4,
        img: [img, imgTwo],
        title: "Local Comercial Puerto Cabello",
        desc: "Descripcion corta",
        price: 11000,
        metrosUno: 100,
        metrosDos: 100,
        habitaciones: 5,
        banos: 2,
        estac: 2,
        ubicacion: "Puerto Cabello",
        tipo: "Local Comercial",
        ubi: 'Ubicacion escrita',
        caracteristicas: ["134 Mts2", "Para 3 personas", "4 Habitaciones", "2 baños", "Cómodo", "Pozo de agua"]
    },
    {
        id: 5,
        img: [img, imgTwo],
        title: "Apto San Diego",
        desc: "Descripcion corta",
        price: 15000,
        metrosUno: 100,
        metrosDos: 100,
        habitaciones: 4,
        banos: 2,
        estac: 2,
        ubicacion: "San Diego",
        tipo: "Apartamento",
        ubi: 'Ubicacion escrita',
        caracteristicas: ["134 Mts2", "Para 3 personas", "4 Habitaciones", "2 baños", "Cómodo", "Pozo de agua"]
    },
    {
        id: 6,
        img: [img, imgTwo],
        title: "Casa Valencia",
        desc: "Descripcion corta",
        price: 16000,
        metrosUno: 100,
        metrosDos: 100,
        habitaciones: 1,
        banos: 2,
        estac: 2,
        ubicacion: "Valencia",
        tipo: "Casa",
        ubi: 'Ubicacion escrita',
        caracteristicas: ["134 Mts2", "Para 3 personas", "4 Habitaciones", "2 baños", "Cómodo", "Pozo de agua"]
    },
    {
        id: 7,
        img: [img, imgTwo],
        title: "Local Guacara",
        desc: "Descripcion corta",
        price: 20000,
        metrosUno: 100,
        metrosDos: 100,
        habitaciones: 5,
        banos: 2,
        estac: 2,
        ubicacion: "Guacara",
        tipo: "Local Comercial",
        ubi: 'Ubicacion escrita',
        caracteristicas: ["134 Mts2", "Para 3 personas", "4 Habitaciones", "2 baños", "Cómodo", "Pozo de agua"]
    },
    {
        id: 8,
        img: [img, imgTwo],
        title: "Casa Puerto Cabello",
        desc: "Descripcion corta",
        price: 30000,
        metrosUno: 100,
        metrosDos: 100,
        habitaciones: 2,
        banos: 2,
        estac: 2,
        ubicacion: "Puerto Cabello",
        tipo: "Casa",
        ubi: 'Ubicacion escrita',
        caracteristicas: ["134 Mts2", "Para 3 personas", "4 Habitaciones", "2 baños", "Cómodo", "Pozo de agua"]
    },
]